apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cert-manager.yaml
- sealed-secrets.yaml
- ingress-nginx.yaml
- linkerd-crds.yaml
- linkerd-control-plane.yaml
- gatekeeper.yaml
- kube-prometheus-stack.yaml
- loki.yaml
- alloy.yaml
- flagger.yaml
- chaos-mesh.yaml
