---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: user-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA4Dt2/T8774mZAPk/4hLFiXO0rh6cRuKi5fV0p6mJqyY8QsA6Y+oR2NuvokV0/fMi0U7Qh2XBKXkU13B4i32XWvX5QSB4ZQdOLDR/gawgPNVotbMnBue7o7PotgiNwWLd3t5P6LNrrZ1yxynOody6+mtrjcRLV8aICcjn2NIKaz02VQWpvcx+jHPFX/R8stk0WFeY1X/aXh8+ALPo5pJ0Go6ydrFZyU62EeGGaH1V1LVYs22UJtwzkkPFDhSpqPUQv3n8JOMZfdU4MsW8AC0lICWSHwOEi7KkPfKDYBtOYF1jzOcn4mypVQrnXhsY1HLFyyv8B68n+HTJj1fgaDA2CGnQUlX4YBWXDCInQVEc3eFYMFoJZi3D/Hi8ufgq1mnBe9bOnZ3t3ZUTfgpqtGmlp1H0ErkKqcakix+/TwfMWmQ9irj2WNk7ia7IXRa/u0F/20Hc+wPPm46iDuSKBVnpNyMNaTD7183RHuDH/EFzHN2LBod8yP6bLf7VjFi2mVtEnu05R77Y81bYQB71ogB8XxIzpBwQHgDD8e/PcXJ0xGjXZa4XayEQ9dt6RzDoeXHjEfPg+4mdMi17WgFTHHqno78gm1ypLV8W98x9WUf1B8xm5iWcN20fBNKfwyHGosZQtTd4MeQyb0k3HNADrqU+cgiiIlzyI1ktXkq9BLIBD6igq/mTTXnQ58/jrno3BNVwkMCjqzm2B2tU827uNH6k=
  template:
    metadata:
      name: postgresql-secret
      namespace: user-app
