apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBv... 
  template:
    metadata:
      name: postgresql-secret
      namespace: postgresql
    type: Opaque