---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: postgresql
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBv5E3RrQdnp+9D32N54ho8NbCqcdPOSNWqE4z7nzGuPlBxBSPJP/JC/eTvTdu55kn8IIiHnsov0ZnG3IJlIo9p8gUBnTmNueft74/8jZ1uFWmR8y6PliuQb51BU/Cf8oEeFlr0rsYvymC50ERcK6IIaZyPUIrftgUMn7AeJoKLUcktJeld+yMERbOjTWb5OS5dF3lgoln25lonEnWHKY+hnzFfvNXRg4MBhjwEJdsJptib0ipVr7p9fbixuhHhN0gSIm5BFo44aP9wCaZjEyDY59qWNwESwVGNUAnovaXwRh3pi4TRk/FyOtpDzx+c/a9JALywZxJPKamCsKJsKt+uK8FzMvqmI8BSWc2r6VI1YqD6aSNBZJKAp8vOYR9PEvh3qpos1h99cyvsN09nfWJfiU1JUVrRbIzfCSw/VRfIDHw2FFgmGeW2v4Z02Aoq+HDIsNkYSbE3qsJV50+8/g8JLTG1gf7nssroF7jkw5EOztUzTBCR2TG7IyltXdKBvcOMWte7blz4D2iCfbhWTmFK/Rr1/vWX9y2kU/FSWa6IkcjXu1G4ZEeufx43DxiDm2dPz585EG8jZzF+Zi8+r3En46jAAIyKGA9B64OFYfX+beb1wGpmpKbWwtXXLn34QpJgKtZuCOk7fj3375YeQmAfBtE7OltLSurKEMxmaMxOtU+jTMySH/+B5UF0nJVYsDfu/YQT3rFp3/9S1ohxAZ0=
  template:
    metadata:
      name: postgresql-secret
      namespace: postgresql
