apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: user-app
  namespace: user-app
spec:
  provider: nginx
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: user-app
  service:
    port: 8080
    targetPort: 8080
  analysis:
    interval: 1m
    threshold: 5
    maxWeight: 50
    stepWeight: 10
