apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gotk-sync.yaml
  - infrastructure-namespaces.yaml
  - infrastructure-sources.yaml
  - infrastructure-releases.yaml
  - infrastructure.yaml
  - apps.yaml
  - monitoring.yaml
  - service-mesh.yaml
  - gatekeeper.yaml
  - postgresql.yaml
  - infrastructure-secrets.yaml
  - infrastructure-canary.yaml
