apiVersion: v1
kind: Namespace
metadata:
  name: {{.Release.Namespace}}
  annotations:
    linkerd.io/inject: {{.Values.linkerd.inject}}
  labels:
    pod-security.kubernetes.io/enforce: {{.Values.podSecurity.enforce}}
    pod-security.kubernetes.io/warn: baseline
