---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgresql-secret
  namespace: user-app
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgA6arRQeVtKHqTFSW2EFiUa+ARhqL6CFXIX9mbvMBJpgqkoEvK8hlTINk9uhYwTZpgUWLOj2HvuubHwL6fcYkt12DhUHUdf4xTE2Rqa4fLmgwU3mdYtt/t2eKOPZxrwXXFX7ChFHpKLjwdCOyfEN/WBJFi76z1XtNpvY0QrbJz1O3X92/fS7GLgZau2c6UkCJrdQWQyYut3IbDWeqoiL+qvy92vg6Pr6f3zTbAv8QByvoaRMCkSzB8aAvBvfOzQHtN6hq6mrwJUMSxLkm+KnsOL3yvlSD+ClijcDnH71F787PobWkE65As9B/nbEO5MRWoAweuLEpvoPB3YbypdhJ2yIKFga4pUGFXAT6j+4ejjPNX60RH39zOiwiKIi9RAkhfzRx0oe57aR7arzulTlFZvSeIaTf2SDW9fwmugxo3QMtit3s5Ja5MWsQ7kBJEdD4Nw8htQaYp4aKdltLWFgxR/GVO4Iqzd//qcoISxNslVExWlO2hJLZ8tKRZUbiPxAW5oRES+V5wl24nD9V1Hh+e/RizxJ/revjMk8q5Qls39x33JUK2jPytcKKy6jc71zj8bdS8iQxR28U46kEb/lJlYvrJk99dZf2uOmNEiKqkJqSyMkIr3RDYmRS4gLw0roAt2m8gByk5Q9D6S2ufm8aUkgBxrPAQBqh8egt58Pr2nrGasT1OyB8vJnRh29mWRKuEvAKeGHa2yUetMJVCgE4c=
  template:
    metadata:
      name: postgresql-secret
      namespace: user-app
