apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-app-secret
  namespace: user-app
spec:
  encryptedData:
    API_KEY: AgBv...
  template:
    metadata:
      name: user-app-secret
      namespace: user-app
    type: Opaque
