apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
  namespace: user-app
data:
  POSTGRES_DB: my_app
  POSTGRES_USER: my_app
  POSTGRES_HOST: postgresql.postgresql.svc.cluster.local
  POSTGRES_PORT: "5432"
